import type { Metadata } from "next";
import { MachineProvider } from "@/app/context/machine-context";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {/* mounted once here so "/" and "/graph" share one running
            machine instance instead of each spinning up their own */}
        <MachineProvider>{children}</MachineProvider>
      </body>
    </html>
  );
}
